AWSTemplateFormatVersion: "2010-09-09"
Description: SRE SLO Demo V2 - Backup Stack

Parameters:
  AppImage:
    Type: String
  PromImage:
    Type: String
  GrafanaImage:
    Type: String

Resources:

  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.1.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.1.1.0/24
      MapPublicIpOnLaunch: true

  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC

  Route:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  SubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref RouteTable

  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: sre-slo-demo-v2-cluster

  ECSExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: sre-slo-v2-ecs-execution-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  ServiceDiscoveryNamespace:
    Type: AWS::ServiceDiscovery::PrivateDnsNamespace
    Properties:
      Name: sre-v2.local
      Vpc: !Ref VPC

  AppDiscoveryService:
    Type: AWS::ServiceDiscovery::Service
    Properties:
      Name: sre-app-v2-service
      NamespaceId: !Ref ServiceDiscoveryNamespace
      DnsConfig:
        DnsRecords:
          - Type: A
            TTL: 10
        RoutingPolicy: MULTIVALUE

  ECSServiceSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP v2
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 5000
          ToPort: 5000
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 9090
          ToPort: 9090
          CidrIp: 0.0.0.0/0

  AppTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: sre-app-v2-task
      RequiresCompatibilities: [FARGATE]
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      ExecutionRoleArn: !GetAtt ECSExecutionRole.Arn
      ContainerDefinitions:
        - Name: app
          Image: !Ref AppImage
          Essential: true
          PortMappings:
            - ContainerPort: 5000

  AppService:
    Type: AWS::ECS::Service
    DependsOn: AppDiscoveryService
    Properties:
      Cluster: !Ref ECSCluster
      LaunchType: FARGATE
      DesiredCount: 1
      ServiceName: sre-app-v2-service
      TaskDefinition: !Ref AppTaskDefinition
      ServiceRegistries:
        - RegistryArn: !GetAtt AppDiscoveryService.Arn
          ContainerName: app
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets: [!Ref PublicSubnet]
          SecurityGroups: [!Ref ECSServiceSG]

  ObservabilityTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: sre-observability-v2-task
      RequiresCompatibilities: [FARGATE]
      Cpu: 1024
      Memory: 2048
      NetworkMode: awsvpc
      ExecutionRoleArn: !GetAtt ECSExecutionRole.Arn
      ContainerDefinitions:
        - Name: prometheus
          Image: !Ref PromImage
          Essential: true
          PortMappings:
            - ContainerPort: 9090
        - Name: grafana
          Image: !Ref GrafanaImage
          Essential: true
          PortMappings:
            - ContainerPort: 3000

  ObservabilityService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ECSCluster
      LaunchType: FARGATE
      DesiredCount: 1
      ServiceName: sre-observability-v2-service
      TaskDefinition: !Ref ObservabilityTaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets: [!Ref PublicSubnet]
          SecurityGroups: [!Ref ECSServiceSG]